Update Dockerfile

diff --git a/Mindustry/Dockerfile b/Mindustry/Dockerfile
--- a/Mindustry/Dockerfile
+++ b/Mindustry/Dockerfile
@@ -58,8 +58,12 @@ WORKDIR /
 # RUN mkdir -p /etc/s6-overlay/s6-rc.d/user/
 # RUN chmod 777 /etc/s6-overlay/s6-rc.d/user/ 
 COPY rootfs/ /
-RUN     echo "Start copy test" && \
-if [ ! -f /etc/s6-overlay/s6-rc.d/app-init/type ]; then echo "Copy failed: type file"; exit 1; fi
+RUN echo "Start copy test" && \
+    if [ ! -f /etc/s6-overlay/s6-rc.d/app-init/type ]; then echo "Copy failed: type file"; exit 1; fi && \
+    touch /etc/s6-overlay/s6-rc.d/app-init/type && \
+    touch /etc/s6-overlay/s6-rc.d/app-init/type2 && \
+
+
 
 
 # Make scripts executable
